version: '3'
services:
  python_cli:
    restart: always
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    container_name: 'python_container'
    working_dir: '/app'
    tty: true
    volumes:
      - ./:/app